# Generated by Django 3.1.3 on 2020-12-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_auto_20201202_1906'),
    ]

    operations = [

    ]
