# Generated by Django 3.1.3 on 2020-12-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_auto_20201202_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='id_producer',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='price',
        ),
        migrations.AddField(
            model_name='storage',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='id_provider',
            field=models.ForeignKey(db_column='id_instrument', on_delete=django.db.models.deletion.RESTRICT, to='storeApp.instrument'),
        ),
    ]
