# Generated by Django 3.1.3 on 2020-12-03 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_auto_20201202_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_instrument',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='id_user_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.userconnection'),
        ),
    ]
