# Generated by Django 3.1.3 on 2020-12-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_auto_20201204_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedInstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instrument', models.ForeignKey(db_column='id_instrument', default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.instrument')),
                ('id_order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.RESTRICT, to='storeApp.order')),
            ],
            options={
                'db_table': 'ordered_instr',
            },
        ),
    ]
