# Generated by Django 3.1.3 on 2020-12-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0005_orderedinstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instrument', models.ForeignKey(db_column='id_instrument', default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.instrument')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
