# Generated by Django 3.1.3 on 2020-12-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0006_cart'),
    ]

    operations = [

    ]
