# Generated by Django 3.1.3 on 2020-12-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0007_remove_storage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='id_instrument',
            field=models.ForeignKey(db_column='id_instrument', default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.instrument'),
        ),
    ]
