# Generated by Django 3.1.3 on 2020-12-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0008_auto_20201204_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
