# Generated by Django 3.1.3 on 2020-12-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0009_auto_20201205_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
