# Generated by Django 3.1.3 on 2020-12-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0010_auto_20201206_0323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_',
        ),
    ]
