# Generated by Django 3.1.3 on 2020-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0011_auto_20201206_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
