# Generated by Django 3.1.3 on 2020-12-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0013_auto_20201208_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='id_address',
            field=models.ForeignKey(db_column='id_address', on_delete=django.db.models.deletion.CASCADE, to='storeApp.address'),
        ),
    ]
